uniform makefile experience
hashicorp/consul-dataplane pull request #344
Opened 2023-11-13 19:08 UTC by wangxinyi7

2023-11-15 15:21 UTC, analogue commented
@wangxinyi7 Please add reviewers that have vested interest and context.  In this case, @wilkermichael would be ideal since he created NET-4834 and took the initiative to track this work.

2023-11-15 17:37 UTC, wangxinyi7 commented
> @wangxinyi7 Please add reviewers that have vested interest and context. In this case, @wilkermichael would be ideal since he created NET-4834 and took the initiative to track this work.

@analogue I think he is in vacation so didn't tag him. Thanks @curtbushko for stepping in to review this PR.

2023-11-15 17:41 UTC, analogue commented
> > @wangxinyi7 Please add reviewers that have vested interest and context. In this case, @wilkermichael would be ideal since he created NET-4834 and took the initiative to track this work.
> 
> @analogue I think he is in vacation so didn't tag him. Thanks @curtbushko for stepping in to review this PR.

Even more reason to tag @wilkermichael since you're leaving breadcrumbs for him to follow on his return should he wish to get up to speed.

2023-11-21 18:27 UTC, curtbushko requested changes
Looks pretty good. 

Feel free to say no to the DOCKER_TARGET request =)

2023-11-22 00:38 UTC, wangxinyi7 commented on Makefile
>  # DOCKER_TARGET is a macro that generates the build and run make targets
Yup, removed the docker_target macro

2023-11-22 00:40 UTC, wangxinyi7 commented on Makefile
> +docker: docker/release-default ## build release-default target
Sorry I think I missed some context here and didn't find the example in the consul-k8s so I didn't update this, maybe could do it in another PR? Or feel free to commit in the PR if it's straightforward to you.

2023-11-22 15:35 UTC, curtbushko commented
@wangxinyi7 It looks like the integration tests are failing.

2023-11-22 15:36 UTC, curtbushko commented
@wangxinyi7 This one too should also be backported all the way to the older release branches

2023-11-23 18:00 UTC, merged